language: csharp
solution: JsonParse.sln
install:
  - nuget restore JsonParse.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release JsonParse.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./JsonParseTest/bin/Release/JsonParseTest.dll